version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven Dependencies...
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/psyco-back.jar
  discard-paths: yes