version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven Dependencies...
  build:
    commands:
      - echo Packaging JAR file...
      - mvn package
  post_build:
    commands:
      - echo Build completed moving JAR file...
      - mv target/*.jar app.jar

artifacts:
  files:
    - app.jar
